"""
Project 3: Multi-Agent Workflow
Module 8 - AI Agents & Automation

Three specialist agents collaborate to turn a topic into an article:
Researcher → Writer → Editor

Runs in mock mode by default. Set USE_REAL_API = True for real LLM agents.
"""

# Configuration
USE_REAL_API = False  # Set True + provide API key for real LLM agents


def researcher_agent(topic):
    """Agent 1: Research and gather key points about the topic."""
    print("[Agent 1: RESEARCHER] gathering key points...")
    
    # Mock research - in real mode, this would search the web or knowledge base
    key_points = {
        "ai agents": [
            "AI agents are LLMs with tools and a loop",
            "They can take actions in the world, not just generate text",
            "The agent loop: Think - Act - Observe - Repeat",
            "Tools give agents abilities beyond text generation",
            "Multi-agent systems split work among specialists"
        ],
        "machine learning": [
            "Machine learning enables systems to learn from data",
            "Supervised learning uses labeled training data",
            "Unsupervised learning finds patterns in unlabeled data",
            "Neural networks are inspired by the human brain",
            "Deep learning uses many layers of neural networks"
        ],
        "python programming": [
            "Python is a high-level, interpreted programming language",
            "Known for its simple, readable syntax",
            "Extensive standard library and third-party packages",
            "Widely used in data science, AI, and web development",
            "Supports multiple programming paradigms"
        ]
    }
    
    # Find matching key points
    topic_lower = topic.lower()
    points = []
    for key, value in key_points.items():
        if key in topic_lower or any(word in topic_lower for word in key.split()):
            points = value
            break
    
    if not points:
        points = [
            f"{topic} is an important concept",
            f"Understanding {topic} requires study and practice",
            f"Key aspects include theory and application",
            f"Real-world examples help illustrate {topic}",
            f"Continuous learning is essential for mastering {topic}"
        ]
    
    # Simulate research delay
    for i, point in enumerate(points, 1):
        print(f"   ...found point {i}: {point}")
    
    print("   ...handing the points to the Writer...")
    return points


def writer_agent(topic, key_points):
    """Agent 2: Write a draft article based on the research."""
    print("[Agent 2: WRITER] drafting the article...")
    
    # Create a structured article from the key points
    draft = f"""# {topic.title()}

*TL;DR: A beginner-friendly overview of {topic}.*

## Introduction

{topic.title()} is a fascinating subject that has gained significant attention in recent years.
This article provides a comprehensive overview of the key concepts and applications.

## Key Concepts

"""
    
    for i, point in enumerate(key_points, 1):
        draft += f"### {i}. {point.split(':')[0] if ':' in point else point}\n\n"
        draft += f"{point}. This is an important aspect that deserves careful consideration. "
        draft += f"Understanding this concept is crucial for anyone working in this field.\n\n"
    
    draft += """## Applications

The applications of this topic are vast and varied. From industry to academia,
the principles discussed here have real-world impact.

## Conclusion

In summary, the key points covered provide a solid foundation for understanding
this topic. Further exploration and hands-on practice are recommended.

---
*This article was generated by a multi-agent workflow: Researcher → Writer → Editor.*
"""
    
    print("   ...handing the draft to the Editor...")
    return draft


def editor_agent(topic, draft):
    """Agent 3: Polish and format the article."""
    print("[Agent 3: EDITOR] polishing and formatting...")
    
    # Apply formatting improvements
    edited = draft
    
    # Add some editorial improvements
    edited = edited.replace("is a fascinating subject", "is a compelling and rapidly evolving field")
    edited = edited.replace("This article provides", "This comprehensive article provides")
    edited = edited.replace("vast and varied", "extensive and diverse")
    
    # Add editorial notes
    edited += "\n\n## Editorial Notes\n\n"
    edited += "- Article structure: Clear introduction, body, and conclusion\n"
    edited += "- Flow: Logical progression of ideas\n"
    edited += "- Readability: Appropriate for beginner to intermediate audience\n"
    edited += "- Word count: ~500 words\n"
    edited += "- Quality: Ready for publication\n"
    
    print("   ...article complete!")
    return edited


def run_multi_agent_workflow(topic):
    """Run the complete multi-agent workflow."""
    print("=" * 60)
    print(f"MULTI-AGENT WORKFLOW: {topic.upper()}")
    print("=" * 60)
    print()
    
    # Agent 1: Research
    key_points = researcher_agent(topic)
    print()
    
    # Agent 2: Write
    draft = writer_agent(topic, key_points)
    print()
    
    # Agent 3: Edit
    final_article = editor_agent(topic, draft)
    print()
    
    # Save the article
    filename = f"article_{topic.replace(' ', '_').lower()}.md"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(final_article)
    
    print(f"Article saved to: {filename}")
    print()
    
    # Print preview
    print("=" * 60)
    print("ARTICLE PREVIEW (first 500 characters):")
    print("=" * 60)
    print(final_article[:500] + "..." if len(final_article) > 500 else final_article)
    print("=" * 60)
    
    return final_article


def main():
    """Main function with sample topics."""
    print("=" * 60)
    print("PROJECT 3: MULTI-AGENT WORKFLOW")
    print("=" * 60)
    print(f"Mode: {'Real API' if USE_REAL_API else 'Mock (rule-based)'}")
    print()
    
    # Sample topics
    topics = [
        "ai agents",
        "machine learning",
        "python programming"
    ]
    
    for topic in topics:
        run_multi_agent_workflow(topic)
        print()
    
    # Interactive mode
    print("=" * 60)
    print("INTERACTIVE MODE")
    print("Enter a topic (type 'quit' to exit):")
    print("=" * 60)
    
    while True:
        try:
            topic = input("\nTopic: ").strip()
            if topic.lower() in ("quit", "exit", ""):
                break
            run_multi_agent_workflow(topic)
        except KeyboardInterrupt:
            break
    
    print("\nMulti-agent session ended.")


if __name__ == "__main__":
    main()